In [3]:
import numpy as np

vec = np.zeros(25)
vec[6:15] = 1
print(vec)


[0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [14]:
vec = np.arange(5, 20)
vec_reversed = vec[::-5]
print(vec_reversed)


[29 24 19 14  9  4]


In [18]:
vec = np.random.rand(5)
half = len(vec) // 2
vec[:half] = np.sort(vec[:half])
vec[half:] = np.sort(vec[half:])[::-1]
print(vec)


[0.16988637 0.73996897 0.83914806 0.80438048 0.00826455]


In [19]:
vec = np.random.uniform(0, 2, 5)
print(vec)


[1.25895462 0.20843987 1.16782771 1.06558652 0.99992793]


In [20]:
arr1 = np.array(["a", "b", "c"])
arr2 = np.array(["V", "U", "W"])
concatenated = np.core.defchararray.add(arr1, arr2)
print(concatenated)


['aV' 'bU' 'cW']


In [31]:
arr = np.random.rand(5, 6)
min_val = arr.min()
max_val = arr.max()
print(f"Min: {min_val}, Max: {max_val}")


Min: 0.009207735377429804, Max: 0.9439492596709396


In [30]:
arr = np.ones((7, 5))
arr[1:-1, 1:-1] = 5
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
arr = np.zeros((4, 5))
np.fill_diagonal(arr[1:], [1, 2, 3])
np.fill_diagonal(arr[:, 1:], [1, 2, 3])
print(arr)


[[0. 1. 0. 0. 0.]
 [1. 0. 2. 0. 0.]
 [0. 2. 0. 3. 0.]
 [0. 0. 3. 0. 1.]]


In [28]:
matrix = np.random.rand(1, 6)
blocks = [matrix[i:i+3, j:j+3] for i in range(8) for j in range(8)]
for block in blocks:
    print(block)


[[0.92478748 0.12050913 0.17471672]]
[[0.12050913 0.17471672 0.14311749]]
[[0.17471672 0.14311749 0.5428272 ]]
[[0.14311749 0.5428272  0.54338285]]
[[0.5428272  0.54338285]]
[[0.54338285]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [21]:
A = np.array([[17, 24, 1, 8, 15],
              [23, 5, 3, 14, 16],
              [40, 6, 13, 20, 22],
              [20, 12, 29, 11, 3],
              [1, 18, 5, 21, 9]])

# Row sums
row_sums = A.sum(axis=1)
# Column sums
col_sums = A.sum(axis=0)
# Diagonal sums
main_diag_sum = np.diag(A).sum()
sec_diag_sum = np.fliplr(A).diagonal().sum()

print(f"Row sums: {row_sums}")
print(f"Column sums: {col_sums}")
print(f"Main diagonal sum: {main_diag_sum}")
print(f"Secondary diagonal sum: {sec_diag_sum}")

# Check if all sums are equal
sums = np.concatenate((row_sums, col_sums, [main_diag_sum, sec_diag_sum]))
if np.max(sums) == np.min(sums):
    print("This is a magic square!")
else:
    print("This is not a magic square.")


Row sums: [ 65  61 101  75  54]
Column sums: [101  65  51  74  65]
Main diagonal sum: 55
Secondary diagonal sum: 55
This is not a magic square.
