In [2]:
def calculate_salary():
    basic_salary = float(input("Enter Basic Salary: "))
    hra = 0.2 * basic_salary
    da = 0.5 * basic_salary
    gross_salary = basic_salary + hra + da
    tax = 0.1 * gross_salary
    net_salary = gross_salary - tax
    
    print(f"HRA: ₹{hra:.2f}")
    print(f"DA: ₹{da:.2f}")
    print(f"Gross Salary: ₹{gross_salary:.2f}")
    print(f"Tax: ₹{tax:.2f}")
    print(f"Net Salary: ₹{net_salary:.2f}")

calculate_salary()

Enter Basic Salary:  400000


HRA: ₹80000.00
DA: ₹200000.00
Gross Salary: ₹680000.00
Tax: ₹68000.00
Net Salary: ₹612000.00


In [4]:
def fibonacci_series():
    n = int(input("Enter the number of terms: "))
    a, b = 0, 1
    print("Fibonacci series:", end=" ")
    for _ in range(n):
        print(a, end=", " if _ < n - 1 else "")
        a, b = b, a + b

fibonacci_series()

Enter the number of terms:  10


Fibonacci series: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34

In [11]:
def calculate_trip_cost():
    try:
        
        distance = float(input("Enter trip distance (in km): "))
        fuel_efficiency = float(input("Enter vehicle fuel efficiency (in km/l): "))
        fuel_price = float(input("Enter fuel price per liter: "))


        if distance < 0 or fuel_efficiency <= 0 or fuel_price < 0:
            print("Inputs must be positive numbers!")
            return


        total_cost = (distance / fuel_efficiency) * fuel_price

    
        print(f"Total cost of the trip: ₹{total_cost:.2f}")
    except ValueError:
        print("Invalid input! Please enter numeric values.")


if __name__ == "__main__":
    print("Road Trip Cost Calculation")
    calculate_trip_cost()

    

Road Trip Cost Calculation


Enter trip distance (in km):  450
Enter vehicle fuel efficiency (in km/l):  8
Enter fuel price per liter:  150


Total cost of the trip: ₹8437.50


In [5]:
library = {}

def add_book(book_id, title, author, availability):
    library[book_id] = {'Title': title, 'Author': author, 'Availability': availability}
    print("Book added successfully.")

def update_availability(book_id, availability):
    if book_id in library:
        library[book_id]['Availability'] = availability
        print("Availability updated successfully.")
    else:
        print("Book ID not found.")

def remove_book(book_id):
    if book_id in library:
        del library[book_id]
        print("Book removed successfully.")
    else:
        print("Book ID not found.")

def display_books():
    if not library:
        print("No books in the library.")
    else:
        for book_id, details in library.items():
            print(f"Book ID: {book_id}, Details: {details}")

while True:
    print("\n1. Add Book\n2. Update Availability\n3. Remove Book\n4. Display All Books\n5. Exit")
    choice = input("Enter your choice: ")
    if choice == "1":
        book_id = input("Enter Book ID: ")
        title = input("Enter Title: ")
        author = input("Enter Author: ")
        availability = input("Enter Availability (Yes/No): ")
        add_book(book_id, title, author, availability)
    elif choice == "2":
        book_id = input("Enter Book ID: ")
        availability = input("Enter Availability (Yes/No): ")
        update_availability(book_id, availability)
    elif choice == "3":
        book_id = input("Enter Book ID to remove: ")
        remove_book(book_id)
    elif choice == "4":
        display_books()
    elif choice == "5":
        break
    else:
        print("Invalid choice.")


1. Add Book
2. Update Availability
3. Remove Book
4. Display All Books
5. Exit


Enter your choice:  1
Enter Book ID:  101
Enter Title:  Python Programming
Enter Author:  John Doe
Enter Availability (Yes/No):  yes


Book added successfully.

1. Add Book
2. Update Availability
3. Remove Book
4. Display All Books
5. Exit


Enter your choice:  3
Enter Book ID to remove:  101


Book removed successfully.

1. Add Book
2. Update Availability
3. Remove Book
4. Display All Books
5. Exit


Enter your choice:  5


In [12]:
import numpy as np

def matrix_operations():
    
    matrix_a = np.random.randint(1, 11, size=(3, 3))
    matrix_b = np.random.randint(1, 11, size=(3, 3))

    
    print("Matrix A:")
    print(matrix_a)
    print("Matrix B:")
    print(matrix_b)

    
    addition_result = matrix_a + matrix_b
    print("\nMatrix Addition:")
    print(addition_result)

    
    multiplication_result = np.dot(matrix_a, matrix_b)
    print("\nMatrix Multiplication:")
    print(multiplication_result)


if __name__ == "__main__":
    print("Matrix Operations")
    matrix_operations()


Matrix Operations
Matrix A:
[[3 9 6]
 [2 1 7]
 [7 1 7]]
Matrix B:
[[ 7  7 10]
 [10  5  1]
 [ 5  3  3]]

Matrix Addition:
[[10 16 16]
 [12  6  8]
 [12  4 10]]

Matrix Multiplication:
[[141  84  57]
 [ 59  40  42]
 [ 94  75  92]]


In [15]:
import pandas as pd

def sales_data_management():
    try:

        product_names = input("Enter product names (comma-separated): ").split(',')
        units_sold = list(map(int, input("Enter units sold (comma-separated): ").split(',')))
        prices = list(map(float, input("Enter prices per unit (comma-separated): ").split(',')))


        if len(product_names) != len(units_sold) or len(units_sold) != len(prices):
            print("Error: Mismatched input lengths!")
            return


        data = {
            "Product Name": product_names,
            "Units Sold": units_sold,
            "Price Per Unit": prices
        }
        df = pd.DataFrame(data)

    
        df["Revenue"] = df["Units Sold"] * df["Price Per Unit"]


        print("\nSales Data:")
        print(df)


        total_revenue = df["Revenue"].sum()
        print(f"\nTotal Revenue: ₹{total_revenue:.2f}")

    
        average_price = df["Price Per Unit"].mean()
        print(f"Average Price Per Unit: ₹{average_price:.2f}")

    
        highest_revenue_product = df.loc[df["Revenue"].idxmax(), "Product Name"]
        print(f"Highest Revenue Product: {highest_revenue_product}")
    except ValueError:
        print("Invalid input! Please ensure all inputs are correctly formatted.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


if __name__ == "__main__":
    sales_data_management()


Enter product names (comma-separated):  SUNSCREEN,LIP-BALM,MASCARA
Enter units sold (comma-separated):  100,250,150
Enter prices per unit (comma-separated):  450,100,650



Sales Data:
  Product Name  Units Sold  Price Per Unit  Revenue
0    SUNSCREEN         100           450.0  45000.0
1     LIP-BALM         250           100.0  25000.0
2      MASCARA         150           650.0  97500.0

Total Revenue: ₹167500.00
Average Price Per Unit: ₹400.00
Highest Revenue Product: MASCARA
